# GitHub Actions workflow
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions

name: CI

on:
  push:
    branches:
      - "*"

  schedule:
    - cron: "0 0 1 * *"  # Every day at 1am

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    if: github.event_name != 'pull_request'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 10.18.0
          - 10.x
          - 12.14.0
          - 12.x
          - 14.15.0
          - 14.x
          - 15.0.0
          - 15.x
          - 16.0.0
          - 16.x
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build the code
        run: npm run build
